### ISSUE TITLE
Add capitalization proofing

### ISSUE THREAD

**Issue by zekemccrary** [zekemccrary/PhoneticEnglish#1]
Capitalized letters need to be converted to lowercase for database search, then converted back after

**Comment by zekemccrary** [comment]
## Issue
Preliminary capitalization is added, some weird issues with capitalizing words containing apostrophes:
#### Hasn't. Doesn't Don't Haven't, I'm
<img width="251" alt="Screenshot 2024-09-15 at 2 40 54 PM" src="https://github.com/user-attachments/assets/084ba035-1b06-4b11-9c8e-7d0146818fd3">

## Possible Solution
Instead of storing words as strings, store them as `Vec<Token::Character(char, bool)>`, which stores whether it is capitalized or not

**Comment by zekemccrary** [comment]
## Changes
Added `AsciiCharacter` struct
Rewrote `tokenize()`, `translate_word()`, `parse()` functions to use `AsciiCharacter`s

## Issues
1. Capitalization issue not solved
2. Apostrophes as quotes before and after words not handled

## To-do
- [x] Add `Token::Apostrophe` enum variant
- [x] Update capitalization to only capitalize one letter of a phoneme
- [ ] Solve capitalization issue somehow?

**Comment by zekemccrary** [comment]
## Changes
Added separate parsing for apostrophes and alphabetic characters in `tokenize()` function

## Issues
1. Words with more phonemes than letters get cut off as a result of zipping `word_str` with `char_vec` in `translate_word()` function
2. Words where the phonemes and letters don't match up directly can have incorrect capitalization

## To-do
- [ ] Fix `translate_word()` function
- [ ] Solve capitalization issue somehow? (I don't think it's possible while using the CMU Pronouncing Dictionary for phonetic translations)
